### ISSUE TITLE
http errors

### ISSUE THREAD

**Issue by huseyiincavus** [curveballjs/http-errors#20]
I am getting an error like this when creating API
error: The argument type 'String' can't be assigned to the parameter type 'Uri'. (argument_type_not_assignable at [http_demo] lib\data\api\category_api.dart:4)
![Ekran Alıntısı](https://user-images.githubusercontent.com/79909536/110234661-ba94a080-7f3c-11eb-86f6-bed1bb8ed764.PNG)

**Comment by evert** [comment]
This bug report does not appear related to the `@curveball/http-errors` package.
